"""add person columns and tor points

Revision ID: 29f946457ea5
Revises: b7bc8987d5b9
Create Date: 2025-09-18 17:10:57.059857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f946457ea5'
down_revision: Union[str, None] = 'b7bc8987d5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knrb_rowers', sa.Column('points_at_time_of_race_sculling', sa.Integer(), nullable=True))
    op.add_column('knrb_rowers', sa.Column('points_at_time_of_race_sweeping', sa.Integer(), nullable=True))
    op.drop_column('knrb_rowers', 'points_at_time_of_race_sculling_points')
    op.drop_column('knrb_rowers', 'points_at_time_of_race_sweeping_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knrb_rowers', sa.Column('points_at_time_of_race_sweeping_points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('knrb_rowers', sa.Column('points_at_time_of_race_sculling_points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('knrb_rowers', 'points_at_time_of_race_sweeping')
    op.drop_column('knrb_rowers', 'points_at_time_of_race_sculling')
    # ### end Alembic commands ###
