"""add position column

Revision ID: 39fc0f36c97d
Revises: 9a968de7f4d7
Create Date: 2025-09-18 15:57:07.092466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39fc0f36c97d'
down_revision: Union[str, None] = '9a968de7f4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knrb_rowers', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knrb_rowers', 'position')
    # ### end Alembic commands ###
