"""initial migration

Revision ID: 9a968de7f4d7
Revises: 
Create Date: 2025-09-18 15:32:19.912538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a968de7f4d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knrb_persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knrb_persons_created_at', 'knrb_persons', ['created_at'], unique=False)
    op.create_table('knrb_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knrb_seasons_created_at', 'knrb_seasons', ['created_at'], unique=False)
    op.create_index('idx_knrb_seasons_year', 'knrb_seasons', ['year'], unique=False)
    op.create_table('knrb_tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('first_date', sa.DateTime(), nullable=False),
    sa.Column('last_date', sa.DateTime(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['knrb_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knrb_tournaments_created_at', 'knrb_tournaments', ['created_at'], unique=False)
    op.create_index('idx_knrb_tournaments_first_date', 'knrb_tournaments', ['first_date'], unique=False)
    op.create_index('idx_knrb_tournaments_last_date', 'knrb_tournaments', ['last_date'], unique=False)
    op.create_index('idx_knrb_tournaments_name', 'knrb_tournaments', ['name'], unique=False)
    op.create_index('idx_knrb_tournaments_season_id', 'knrb_tournaments', ['season_id'], unique=False)
    op.create_index('idx_knrb_tournaments_type', 'knrb_tournaments', ['type'], unique=False)
    op.create_table('knrb_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('boat_category_code', sa.String(length=32), nullable=False),
    sa.Column('match_generated_code', sa.String(length=32), nullable=False),
    sa.Column('match_category_name', sa.String(length=256), nullable=True),
    sa.Column('boat_category_name', sa.String(length=256), nullable=False),
    sa.Column('gender_type', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('full_name_with_addition', sa.String(length=512), nullable=False),
    sa.Column('name_with_addition', sa.String(length=256), nullable=False),
    sa.Column('code_with_addition', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['knrb_tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knrb_matches_boat_category_code', 'knrb_matches', ['boat_category_code'], unique=False)
    op.create_index('idx_knrb_matches_boat_category_name', 'knrb_matches', ['boat_category_name'], unique=False)
    op.create_index('idx_knrb_matches_code', 'knrb_matches', ['code'], unique=False)
    op.create_index('idx_knrb_matches_code_with_addition', 'knrb_matches', ['code_with_addition'], unique=False)
    op.create_index('idx_knrb_matches_created_at', 'knrb_matches', ['created_at'], unique=False)
    op.create_index('idx_knrb_matches_date', 'knrb_matches', ['date'], unique=False)
    op.create_index('idx_knrb_matches_full_name', 'knrb_matches', ['full_name'], unique=False)
    op.create_index('idx_knrb_matches_full_name_with_addition', 'knrb_matches', ['full_name_with_addition'], unique=False)
    op.create_index('idx_knrb_matches_gender_type', 'knrb_matches', ['gender_type'], unique=False)
    op.create_index('idx_knrb_matches_name', 'knrb_matches', ['name'], unique=False)
    op.create_index('idx_knrb_matches_name_with_addition', 'knrb_matches', ['name_with_addition'], unique=False)
    op.create_index('idx_knrb_matches_tournament_id', 'knrb_matches', ['tournament_id'], unique=False)
    op.create_table('knrb_races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('progression_information', sa.String(length=256), nullable=True),
    sa.Column('environment_information', sa.String(length=256), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('is_finals_race', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['knrb_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knrb_races_created_at', 'knrb_races', ['created_at'], unique=False)
    op.create_index('idx_knrb_races_match_id', 'knrb_races', ['match_id'], unique=False)
    op.create_table('knrb_crews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['knrb_races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knrb_coaches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crew_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crew_id'], ['knrb_crews.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['knrb_persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knrb_coaches_created_at', 'knrb_coaches', ['created_at'], unique=False)
    op.create_index('idx_knrb_coaches_crew_id', 'knrb_coaches', ['crew_id'], unique=False)
    op.create_index('idx_knrb_coaches_person_id', 'knrb_coaches', ['person_id'], unique=False)
    op.create_table('knrb_coxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crew_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crew_id'], ['knrb_crews.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['knrb_persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knrb_coxes_created_at', 'knrb_coxes', ['created_at'], unique=False)
    op.create_index('idx_knrb_coxes_crew_id', 'knrb_coxes', ['crew_id'], unique=False)
    op.create_index('idx_knrb_coxes_person_id', 'knrb_coxes', ['person_id'], unique=False)
    op.create_table('knrb_race_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('crew_id', sa.Integer(), nullable=False),
    sa.Column('final_time', sa.Float(), nullable=True),
    sa.Column('final_time_string', sa.String(length=256), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('did_not_finish', sa.Boolean(), nullable=False),
    sa.Column('did_not_start', sa.Boolean(), nullable=False),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('percentage_of_golden_standard', sa.Float(), nullable=True),
    sa.Column('absolute_golden_standard', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crew_id'], ['knrb_crews.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['knrb_races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knrb_rowers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crew_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crew_id'], ['knrb_crews.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['knrb_persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knrb_rowers_created_at', 'knrb_rowers', ['created_at'], unique=False)
    op.create_index('idx_knrb_rowers_crew_id', 'knrb_rowers', ['crew_id'], unique=False)
    op.create_index('idx_knrb_rowers_person_id', 'knrb_rowers', ['person_id'], unique=False)
    op.create_table('knrb_race_result_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_result_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.Integer(), nullable=False),
    sa.Column('split_time', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_finish_time', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['race_result_id'], ['knrb_race_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knrb_race_result_times_created_at', 'knrb_race_result_times', ['created_at'], unique=False)
    op.create_index('idx_knrb_race_result_times_race_result_id', 'knrb_race_result_times', ['race_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_knrb_race_result_times_race_result_id', table_name='knrb_race_result_times')
    op.drop_index('idx_knrb_race_result_times_created_at', table_name='knrb_race_result_times')
    op.drop_table('knrb_race_result_times')
    op.drop_index('idx_knrb_rowers_person_id', table_name='knrb_rowers')
    op.drop_index('idx_knrb_rowers_crew_id', table_name='knrb_rowers')
    op.drop_index('idx_knrb_rowers_created_at', table_name='knrb_rowers')
    op.drop_table('knrb_rowers')
    op.drop_table('knrb_race_results')
    op.drop_index('idx_knrb_coxes_person_id', table_name='knrb_coxes')
    op.drop_index('idx_knrb_coxes_crew_id', table_name='knrb_coxes')
    op.drop_index('idx_knrb_coxes_created_at', table_name='knrb_coxes')
    op.drop_table('knrb_coxes')
    op.drop_index('idx_knrb_coaches_person_id', table_name='knrb_coaches')
    op.drop_index('idx_knrb_coaches_crew_id', table_name='knrb_coaches')
    op.drop_index('idx_knrb_coaches_created_at', table_name='knrb_coaches')
    op.drop_table('knrb_coaches')
    op.drop_table('knrb_crews')
    op.drop_index('idx_knrb_races_match_id', table_name='knrb_races')
    op.drop_index('idx_knrb_races_created_at', table_name='knrb_races')
    op.drop_table('knrb_races')
    op.drop_index('idx_knrb_matches_tournament_id', table_name='knrb_matches')
    op.drop_index('idx_knrb_matches_name_with_addition', table_name='knrb_matches')
    op.drop_index('idx_knrb_matches_name', table_name='knrb_matches')
    op.drop_index('idx_knrb_matches_gender_type', table_name='knrb_matches')
    op.drop_index('idx_knrb_matches_full_name_with_addition', table_name='knrb_matches')
    op.drop_index('idx_knrb_matches_full_name', table_name='knrb_matches')
    op.drop_index('idx_knrb_matches_date', table_name='knrb_matches')
    op.drop_index('idx_knrb_matches_created_at', table_name='knrb_matches')
    op.drop_index('idx_knrb_matches_code_with_addition', table_name='knrb_matches')
    op.drop_index('idx_knrb_matches_code', table_name='knrb_matches')
    op.drop_index('idx_knrb_matches_boat_category_name', table_name='knrb_matches')
    op.drop_index('idx_knrb_matches_boat_category_code', table_name='knrb_matches')
    op.drop_table('knrb_matches')
    op.drop_index('idx_knrb_tournaments_type', table_name='knrb_tournaments')
    op.drop_index('idx_knrb_tournaments_season_id', table_name='knrb_tournaments')
    op.drop_index('idx_knrb_tournaments_name', table_name='knrb_tournaments')
    op.drop_index('idx_knrb_tournaments_last_date', table_name='knrb_tournaments')
    op.drop_index('idx_knrb_tournaments_first_date', table_name='knrb_tournaments')
    op.drop_index('idx_knrb_tournaments_created_at', table_name='knrb_tournaments')
    op.drop_table('knrb_tournaments')
    op.drop_index('idx_knrb_seasons_year', table_name='knrb_seasons')
    op.drop_index('idx_knrb_seasons_created_at', table_name='knrb_seasons')
    op.drop_table('knrb_seasons')
    op.drop_index('idx_knrb_persons_created_at', table_name='knrb_persons')
    op.drop_table('knrb_persons')
    # ### end Alembic commands ###
