"""add person columns and tor points

Revision ID: b7bc8987d5b9
Revises: 39fc0f36c97d
Create Date: 2025-09-18 16:55:20.286804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7bc8987d5b9'
down_revision: Union[str, None] = '39fc0f36c97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knrb_persons', sa.Column('sculling_points_total', sa.Integer(), nullable=True))
    op.add_column('knrb_persons', sa.Column('sweeping_points_total', sa.Integer(), nullable=True))
    op.add_column('knrb_persons', sa.Column('year_of_birth', sa.Integer(), nullable=True))
    op.add_column('knrb_persons', sa.Column('current_rowing_club', sa.String(length=256), nullable=True))
    op.add_column('knrb_rowers', sa.Column('points_at_time_of_race_sculling_points', sa.Integer(), nullable=True))
    op.add_column('knrb_rowers', sa.Column('points_at_time_of_race_sweeping_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knrb_rowers', 'points_at_time_of_race_sweeping_points')
    op.drop_column('knrb_rowers', 'points_at_time_of_race_sculling_points')
    op.drop_column('knrb_persons', 'current_rowing_club')
    op.drop_column('knrb_persons', 'year_of_birth')
    op.drop_column('knrb_persons', 'sweeping_points_total')
    op.drop_column('knrb_persons', 'sculling_points_total')
    # ### end Alembic commands ###
