"""field length update

Revision ID: c0353412156d
Revises: 250d55fc41ee
Create Date: 2025-09-19 08:38:14.528930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0353412156d'
down_revision: Union[str, None] = '250d55fc41ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knrb_matches', 'match_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knrb_matches', 'match_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
